version: 2
jobs:
  build:
    docker:
    - image: circleci/node:latest
    steps:
    - checkout
    - run:
        command: echo ${FAKETOKEN}
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
    - build
