version: 2.1
jobs:
  build:
    machine:
      image: circleci/classic:201711-01
  
    steps:
    - run:
        name: this will fail
        command: exit 1

workflows:
  version: 2
  my-build-workflow:
    jobs:
    - build
