version: 2.1

jobs:
  docker-hub-test:
    machine: true
    steps:
      - run: 
          name: Docker Hub login if available
          command: |
            if [ -n "$DOCKERHUB_USERNAME" ]; then
              docker login --username $DOCKERHUB_USERNAME --password $DOCKERHUB_PASSWORD
            else
              echo "Docker Hub credentials unavailable, pulling anonymously"
            fi
      - run: docker pull circleci/ruby:2.7
      - run: echo "hello"

workflows:
  docker-hub-test:
      jobs:
        - docker-hub-test
