version: 2.1
jobs:
  build1:
    docker:
    - image: circleci/node
    steps:
    - checkout
    - run: echo $HELLO
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
    - build1:
        context:
          - topsecret
