version: 2.1
jobs:
  build:
    docker:
    - image: circleci/node:latest
    steps:
    - checkout
    - run:
        name: say hi
        command: echo "hello"
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
    - build
