hoversion: 2
jobs:
  build:
    machine:
      image: circleci/classic:201711-01
  
    steps:
    - run:
        name: say hi
        command: |
        wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        sudo apt-get update
workflows:
  version: 2
  my-build-workflow:
    jobs:
    - build
