version: 2
jobs:
  build:
    machine:
      image: circleci/classic:201711-01
  
    steps:
    - run:
        name: update apt
        command: update apt-get
workflows:
  version: 2
  my-build-workflow:
    jobs:
    - build
