version: 2.1
jobs:
  build:
    docker:
    - image: circleci/node
    steps:
    - checkout
    - run:
        name: say hi
        command: sleep 125
        
  deploy:
    docker:
    - image: circleci/node
    steps:
    - checkout
    - run:
        name: say hi
        command: sleep 124
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
    - build:
        context: Context1
    - deploy
