version: 2
jobs:
  build-and-test:
    macos:
      xcode: "10.2.1"
    steps:
      - checkout
      - run:
          name: Fetch CocoaPods Specs
          command: |
            curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf
      - run:
          name: Install CocoaPods
          command: pod install --verbose

      - run:
          name: Build and run tests
          command: fastlane scan
          environment:
            SCAN_DEVICE: iPhone 8
            SCAN_SCHEME: WebTests

      - store_test_results:
          path: test_output/report.xml
      - store_artifacts:
          path: /tmp/test-results
          destination: scan-test-results
      - store_artifacts:
          path: ~/Library/Logs/scan
          destination: scan-logs
  otherbuild:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: 
        command: echo "hello"

workflows:
  version: 2
  build-test-lint:
    jobs:
      - otherbuild
      - build-and-test
