version: 2.1
jobs:
  build:
    machine:
      image: circleci/classic:201711-01
  
    steps:
    - run:
        name: say hi
        command: echo "hi!"

workflows:
  version: 2
  my-build-workflow:
    jobs:
    - build
