version: 2
jobs:
  build:
    docker:
    - image: circleci/node:latest
    steps:
    - checkout
    - run:
        name: say hi via context
        command: |
          exit 1
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
    - build:
        context: sandbox-context
