version: 2
jobs:
  build:
    docker:
    - image: circleci/node:latest
    steps:
    - checkout
    - run:
        name: say hi
        command: |
          echo ${SAY_HELLO}
          echo "test"
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
    - build:
        context: test1
