  
version: 2.1
jobs:
  build:
    docker:
    - image: circleci/node
    steps:
    - checkout
    - run: |
        if [ -z "$NICK_TEST" ]; then
          echo "No NICK_TEST is set! Failing..."
          exit 1;
        else
          echo "Credentials are available. Let's fetch the data!"
        fi
        
  deploy:
    docker:
    - image: circleci/node
    steps:
    - checkout
    - run:
        name: say hi
        command: sleep 124
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
    - build:
        context: everyone
    - deploy
