hoversion: 2
jobs:
  build:
    machine:
      image: circleci/classic:201711-01
  
    steps:
    - run:
        name: say hi
        command: |
        apt-key list
workflows:
  version: 2
  my-build-workflow:
    jobs:
    - build
